spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/astrodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: changeme
